[Ready to Review] Implement Multi-Interface Initialisation and Management in CLI
EXA-UQ/EXAUQ-Toolbox pull request #282
Opened 2024-08-30 14:15 UTC by mbjohns

### Updated PR Description:

This PR expands and enhances the CLI for managing multiple hardware interfaces within a workspace. While it retains the core functionality outlined in the issue and original PR description, it also introduces several new features and adjustments to address practical requirements identified during implementation.

### Key Changes

1. CLI Workspace Initialisation
- Planned:
    - The `initialise_app` method now allows paths to hardware parameter files during workspace creation.
    - Prompts guide the user through creating new interfaces if no paths are provided.
    - Interfaces are saved in `hardware_params_<interface_name>.json` files.
- Implemented:
    - A rich, interactive workflow for interface setup, with improved user prompts and validations.
    - Users can choose between an interactive setup mode or loading parameters from an existing JSON file.
    - Interfaces can be assigned levels during setup, stored alongside other configurations.

2. Adding Interfaces to Existing Workspaces
- Planned:
	- A new CLI command (`do_add_interface`) to add interfaces interactively or via file input.
- Implemented:
	- `do_add_interface` includes detailed error handling for JSON file validation and user inputs.
	- Added support for dynamically updating and reinitialising the job manager when a new interface is added.

3. Interface Listing and Details Commands
- Planned:
	- A `do_list_loaded_interfaces` command to display interface names and details.
- Implemented:
	- Renamed to `do_list_interfaces`, with extended functionality:
	- Lists interface names, levels, hosts, users, and active job counts.
	- Displays job counts dynamically fetched from the job manager.

4. Submit Command Enhancements
- Planned:
	- None explicitly stated in the issue.
- Implemented:
	- Added a `--level` flag to the submit command, allowing users to target specific interface levels.
	- Extended input validation and enhanced the submission pipeline to support levels.

5. Documentation Updates
- Planned:
	- Update documentation with new workflows and examples.
- Implemented:
	- Significantly expanded CLI walkthroughs with detailed examples for workspace initialisation, interface addition, job submission, and interface listing.
	- Added notes for advanced CLI usage, such as specifying interface levels.

### Divergences and Additional Features

- Enhanced Prompts: Improved user prompts and validations, ensuring intuitive and (hopefully) error-resilient workflows.
- Dynamic Job Manager Updates: The job manager is now re-initialised when interfaces are added, ensuring seamless operation.
- Extended Submit Command: The `--level` flag was not part of the original scope but enhances flexibility in targeting hardware interfaces.

### Remaining Tasks
- Consider if a `do_show_interface` command for detailed interface insights is necessary.
- Consider whether to add interface activation/deactivation functionality (deferred for future enhancement).

### Acceptance Criteria
- The application now supports creating workspaces with multiple interfaces via interactive or file-based inputs.
- Users can add interfaces to existing workspaces, specify levels, and list details through the CLI.
- Documentation has been updated to reflect changes, with examples.

*Note to reviewer: Sorry this is such a monster PR!*

Closes #281 & Closes #83

2024-12-10 11:26 UTC, mbjohns commented on exauq/app/cli.py
> +                self._render_error(f"Invalid value -- {e}")
Thank you for your detailed feedback! I've addressed the concerns by adding a validation method within the CLI class to ensure interface names are unique and follow valid naming rules. The interactive prompt now allows users to retry invalid inputs immediately, so they don't have to restart the whole process. The `_validate_interface_name` method catches duplicate names, ensuring a smoother experience and preventing the bug you highlighted.

2024-12-10 11:37 UTC, mbjohns commented on exauq/app/startup.py
> +def make_int_parser(
Good suggestion. Done.

2024-12-11 16:20 UTC, HarryWhiteRSE requested changes
Still a bit of an issue with the repeated name. It is fine upon initialisation of the workspace and it gracefully requests a new name. I've added a few suggestions as to potential bug fixes for implementing this with a file and also for the `add_interface` command. I would certainly recommend investigating the `factory` -> `factory_add` one further to really see what is going on there. 

Everything else looks good and the interactive prompt is much nicer to use alongside a much neater summary table! 🚀

2024-12-12 12:26 UTC, mbjohns commented on exauq/app/cli.py
> +                    self._render_error(f"Invalid value -- {e}")
Thanks for the suggestion! I agree that a positive integer check is necessary. I've implemented a `make_pos_int_parser` method in the `startup` module and applied it to the `level` parameter in `UnixServerScriptInterfaceFactory`. Ideally, I'd like to move the name validation logic to the factory class, but I need to find a clean solution for tracking existing interface names and ensuring the factory is aware of them. I'll revisit this once I've worked that out.

2024-12-12 12:29 UTC, mbjohns commented on exauq/app/cli.py
> +
See above.

2024-12-12 16:46 UTC, mbjohns commented on exauq/app/cli.py
> +            self._finalise_hardware_setup(factory, factory_cls)
Thanks for the suggestion! I've implemented something similar, incorporating a few tweaks along the way.

2024-12-13 09:03 UTC, HarryWhiteRSE approved these changes
LGTM! 🚀 

This is a great addition to the job management side of the Toolbox! I think it would be worth opening a more long-term issue to refactor some of this due to the size of the CLI class, however, all the functionality is there and it now feels very robust!

2024-12-13 09:08 UTC, merged